version: '3.6'
networks:
  kafka-example-network:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
     - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=ocsen_zookeeper
      - ZOO_SERVER_PASSWORDS=ocsen_zookeeper_password
    networks:
      - kafka-example-network

  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka.example.com
    ports:
      - '9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_ZOOKEEPER_USER=ocsen_zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=ocsen_zookeeper_password
      - KAFKA_INTER_BROKER_USER=ocsen_inter
      - KAFKA_INTER_BROKER_PASSWORD=ocsen_inter_password
      - KAFKA_BROKER_USER=ocsen_broker
      - KAFKA_BROKER_PASSWORD=ocsen_broker_password
      # - KAFKA_CERTIFICATE_PASSWORD=myCertificatePassword
    # volumes:
    #   - './kafka-key/kafka.keystore.jks:/opt/bitnami/kafka/conf/certs/kafka.keystore.jks:ro'
    #   - './kafka-key/kafka.truststore.jks:/opt/bitnami/kafka/conf/certs/kafka.truststore.jks:ro'
    networks:
      - kafka-example-network